### PR TITLE
Add instant alerts data to the myFT schema

### PR DESCRIPTION
**Pull request by phamann**
To allow us to track within beacon.

Requires: https://github.com/Financial-Times/next-myft-api/pull/251

### CODE REVIEW

**Comment by laurieboyes** [comment]
Worth adding the new properties to the test file? https://github.com/Financial-Times/spoor-enrichment/blob/f9c7f18e74dc3dd9694e931423d0f0318467159f/tests/server/transforms/myft-api.spec.js

**Comment by phamann** [comment]
@laurieboyes done

**Comment by commuterjoy** [comment]
+1

**Comment by laurieboyes** [comment]
👍

**Comment by phamann** [comment]
I can now see the data in the myft api so safe to merge.

**Pull request merged**
