### PR TITLE
getting content id from rootContentId property

### PR DESCRIPTION
**Pull request by wheresrhys**
A few things to think about here

I send the content id as rootContentId rather than contentId or content.uuid because, say a click happens on a link to another article on an article page, and that click also carries a content id, which item of content should that event be decorated with? - that of the article I'm on or that of the article I'm going to? By preferring rootContentId to content.uuid I'm going with the former, and I\ve given it  a distinctive property name as I don't want any other events to clobber the page's content id with their own, but I don't know if it's the right choice. 

How can we make sure we're clear about what the item of content an event is decorated with means. For a page:view it's obvious, but for a click on a link on a page it would be very easy for things to get confused.

Or should we have to make a choice? Could it make sense to decorate events with multiple items of content? How would the sender of the event specify where to find content & concept ids? How could spoor cope with this (both technically and in being explicit about why a given annotation is there)

### CODE REVIEW

**Comment by chrisbrownuk** [comment]
Yes, I'd agree that the event should have details of the page that it is
on, so in the link example it is the page that the link is on, not the page
that the link is pointing at.  That being said, the link example does also
need details of which link is being clicked, since there may be more than
one link to the same destination page, so these need to be differentiated.

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 15 March 2016 at 17:36, Rhys Evans <notifications@github.com> wrote:

> A few things to think about here
>
> I send the content id as a rootContentId rather than contentId or
> content.uuid because, say a click happens on a link to another article on
> an article page, and that click also carries a content id, which item of
> content should that event be decorated with? - that of the article I'm on
> or that of the article I'm going to? By preferring rootContentId to
> content.uuid I'm going with the former, and I don't want any other events
> to clobber the page's content id with their own, but I don't know if it's
> the right choice.
>
> How can we make sure we're clear about what the item of content an event
> is decorated with means. For a page:view it's obvious, but for a click on a
> link on a page it would be very easy for things to get confused.
>
> Or should we have to make a choice? Could it make sense to decorate events
> with multiple items of content? How would the sender of the event specify
> where to find content & concept ids? How could spoor cope with this (both
> technically and in being explicit about why a given annotation is there)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Financial-Times/spoor-enrichment/pull/274
> Commit Summary
>
>    - getting content id from rootContentId property
>
> File Changes
>
>    - *M* server/utils/get-article-uuid.js
>    <https://github.com/Financial-Times/spoor-enrichment/pull/274/files#diff-0>
>    (6)
>
> Patch Links:
>
>    - https://github.com/Financial-Times/spoor-enrichment/pull/274.patch
>    - https://github.com/Financial-Times/spoor-enrichment/pull/274.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/pull/274>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by commuterjoy** [comment]
But given the context (by definition) is contextual to each type of event then does it matter if we overload content.uuid with different meanings? Id argue not.

However in the case the click/cta event I agree we need something like a content.uuid (current page) and destination.uuid (target page)

**Comment by wheresrhys** [comment]
Context is also the only thing guaranteed to go in to NGDA, which may lead to overloading/abuse/accidental clashes. 

If I was going to design the event model from scratch now I might go for a `root` object and a `meta` object. `context` is... err... well, *everything's* contextual, isn't it.

Pending that, does this PR (and the related sending of rootContentId, rootConceptId, rootTaxonomy from stream & atricles) get a :+1: for now?

**Comment by wheresrhys** [comment]
> does it matter if we overload content.uuid with different meanings?

I think it does as most of the time it means 'the article the user is viewing' and unless there's some way of being explicit about when it doesn't mean this people will assume it always means this. Which will lead to confusion in people's interpretation and understanding of the data, and ultimately to mistakes in reporting and decision making

**Comment by commuterjoy** [comment]
+1

but I need to think about the semantics of all of this at some point.

**Comment by wheresrhys** [comment]
yep we all do

**Pull request merged**
