### PR TITLE
Monitor the time.offset

### PR DESCRIPTION
**Pull request by commuterjoy**
/cc @georgecrawford thought this might be interesting as per our chat this morning

### CODE REVIEW

**Comment by georgecrawford** [comment]
Hmm. I think the offset might be in ms. Need to check the o-tracking and ft-app source, but the o-tracking event model docs use ms.

**Comment by georgecrawford** [comment]
Yep, @commuterjoy, this should be in **ms**: https://github.com/Financial-Times/o-tracking/blob/master/src/javascript/core/send.js#L40

**Comment by commuterjoy** [comment]
Yup, I fixed in #446 - thanks!

**Comment by georgecrawford** [comment]
👍

**Pull request merged**
