### PR TITLE
FT regions

### PR DESCRIPTION
**Pull request by markstephens**
Update to match FT's regions

### CODE REVIEW

**Comment by commuterjoy** [comment]
+1 you'll need to fix the tests

**Comment by markstephens** [comment]
didn't realise geo enrichment used ft regions too, i was looking at maxmind test..

**Comment by markstephens** [comment]
@commuterjoy Ok to merge. How does it get released?

**Comment by commuterjoy** [comment]
@markstephens merge and watch the build ... 

https://circleci.com/gh/Financial-Times/spoor-enrichment

**Pull request merged**
