### PR TITLE
Fix isStaff

### PR DESCRIPTION
**Pull request by commuterjoy**
Removing this annotation in favour of the more accurate `user-status` transform. 

/cc @markstephens can you fix downstream please?

### CODE REVIEW

**Comment by commuterjoy** [comment]
Also @georgecrawford https://github.com/Financial-Times/spoor-consumer/blob/ee8bb8cafd2a202fa3946a40300477368cfde274/sinks/keen-apps.js#L154

**Comment by markstephens** [comment]
@commuterjoy I want to fix downstream, what's the format/output of the user-status enrichment?

**Comment by commuterjoy** [comment]
@markstephens http://spoor-docs.herokuapp.com/annotations#user

i.e. `subscriptions.staff`

**Comment by markstephens** [comment]
Oh, ok, I did look at spoor docs but was looking for a user-status enrichment..

**Pull request merged**
