### PR TITLE
Regions

### PR DESCRIPTION
**Pull request by commuterjoy**
- [ ] Add web app and ft.com regions

### CODE REVIEW

**Comment by commuterjoy** [comment]
@georgecrawford does the app send editions with it's events?

@markstephens likewise, how does FT do this?

I'm thinking of just having a standard property in `context`, but then also plucking it from the cookie where needed.

```
{ 
   "context": {
      "edition": "uk"
   }
}
```

**Comment by georgecrawford** [comment]
Hi. Yes, we send `context.edition`, an enum of `dynamic, morning, weekend`. We also send `context.region`, which can be one of `us, uk, asia, europe, middleeast, latam, india`.

**Comment by markstephens** [comment]
ft.com doesn't have an edition, it might have a region.
ePaper does have an edition, I think it's in `context.content.edition`

**Comment by commuterjoy** [comment]
> ft.com doesn't have an edition, it might have a region.

ah, ok - so edition refers to the whole thing and region refers to the front-page we serve them. I didn't appreciate that distinction.

`context.region` seems like a sensible standard for *region* so I'll use that.

**Comment by commuterjoy** [comment]
@georgecrawford is there anything to indicate that some has expressed a preference for a region that is different to the one we would have given them by the default location?

**Comment by georgecrawford** [comment]
We currently only send `context.region`, i.e. the actual regional edition on display. We could also send values to indicate both preferred region (where `automatic` is the default), and the user's actual geoip region. It'd be good to standardise those keys in case we were to start sending that data.

`context.geoip_region` and `context.preferred_region`, perhaps?

**Comment by commuterjoy** [comment]
closing until it comes up on the data quality backlog, at which point we can align across teams

**Pull request closed without merging**
