### PR TITLE
Passes the country name and continent code to ammit

### PR DESCRIPTION
**Pull request by GlynnPhillips**
This will be used by ammit to do location based cohorting.

The following headers will be sent to Ammit
`ft-ammit-country`
`ft-ammit-continent-code`

I have also added some tests to the pipeline as part of this commit. The
reasoning for doing this is that some of the transforms have a
dependency on another transform being run first. My change required me
to reorder some of the transforms and I found it quite time consuming to
figure out if I was going to break other transforms. These tests should
help document the dependencies for future changes.

@commuterjoy @tom-parker @adambraimbridge

### CODE REVIEW

**Comment by GlynnPhillips** [comment]
Opps small change has now broken the tests so will look at this again before needing a review

**Comment by GlynnPhillips** [comment]
@commuterjoy @tom-parker @adambraimbridge Tests now fixed.

**Comment by adambraimbridge** [comment]
👍

**Comment by tom-parker** [comment]
I think the RFV and myFT transforms in the second block rely on the UUID which comes from the session transform so we might not be able to move this to the second lot of transforms?

You might just need to annotate the user property with the session data in the first lot of transforms and then extend this with the AB data in the second lot.

**Comment by commuterjoy** [comment]
> RFV and myFT transforms

or move these to a third block?

**Comment by GlynnPhillips** [comment]
@tom-parker @commuterjoy now updated

**Comment by tom-parker** [comment]
Looks good to me

**Pull request merged**
