### PR TITLE
Revert to 100% traffic for prod device atlas instance

### PR DESCRIPTION
**Pull request by tom-parker**
cc @markstephens @commuterjoy

### CODE REVIEW

**Comment by commuterjoy** [comment]
Was the node version no good?

**Comment by commuterjoy** [comment]
+1

**Comment by tom-parker** [comment]
@commuterjoy the node version is more reliable I think and seemingly giving more consistent results so Mark has shipped it to the original production end point

**Comment by commuterjoy** [comment]
javascript ftw!

**Comment by markstephens** [comment]
Yes, exactly.


--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 4 November 2015 at 12:31, Tom Parker <notifications@github.com> wrote:

> @commuterjoy <https://github.com/commuterjoy> the node version is more
> reliable I think and seemingly giving more consistent results so Mark has
> shipped it to the original production end point
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/pull/154#issuecomment-153706638>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Pull request merged**
