### PR TITLE
Add event headers to egest

### PR DESCRIPTION
**Pull request by commuterjoy**
By exposing these properties this will ultimately let us hide the `ingest` portion of the egest event stream, which we can keep private (internally inside the stream). It will also drastically let us reduce the amount of data being transferred out via Kinesis.

/cc @adambraimbridge @georgecrawford @markstephens @lc512k

### CODE REVIEW

**Comment by adambraimbridge** [comment]
Is it possible this might risk sending sensitive information from the headers to (e.g.) keen? 

If I recall correctly, I did something similar with avro transforms, which I had to undo because some email addresses were in the`event.headers()`.

**Comment by commuterjoy** [comment]
It it a risk, although keen.io doesn't import top level annotations by default. Perhaps I should just scrub the cookie.

**Comment by adambraimbridge** [comment]
👍

**Comment by markstephens** [comment]
+1 for reducing the message size in Kinesis - should help our throughput issues.
Good shout by Adam about PII.
We pick up some cookie data at the moment, so have to think of a way around it if you're scrubbing the cookies.
(We're also using ingest directly, so will have to flip to the ingest within egest.)

**Comment by commuterjoy** [comment]
ok, I've just set `cookie` to undefined in that object.

**Pull request merged**
