### PR TITLE
Decorate anonymous events with a propensity score

### PR DESCRIPTION
**Pull request by commuterjoy**
/cc @tom-parker @akilananb 

This will be useful to start to analyse the types of anonymous people doing things on next.ft.com

- [x] Scope to next page/view traffic
- [ ] Request rate rise from the API gateway team
- [x] Add high/low bandings

### CODE REVIEW

**Comment by tom-parker** [comment]
:+1:

**Comment by akilananb** [comment]
Looks good..Won't be a problem using cookie right older ones...? Like the one we had it for cohort.

**Comment by commuterjoy** [comment]
@akilananb i think the only place the SIVISITOR value exists is in the cookie, so should be fine.

**Comment by akilananb** [comment]
Aah ok..Thanks for the info.

**Pull request merged**
