### PR TITLE
Enrich AMP events with Ammit segmentation

### PR DESCRIPTION
**Pull request by georgecrawford**
Given that we have AMP data in Keen, and we use barrier guru, we should be able to see Ammit enrichment as well.

### CODE REVIEW

**Comment by commuterjoy** [comment]
@tom-parker you ok with the load? if so +1 from me.

**Comment by tom-parker** [comment]
Should be fine, how much load are we talking?

Am I missing something here though, why do you need the allocations on AMP events?

**Comment by georgecrawford** [comment]
@tom-parker I thought it'd be important for us to be able to tell which users were subject to tests which affect barriers, such as pricing tests. We'll also likely be running other barrier-related AB tests for AMP soon enough.

**Comment by georgecrawford** [comment]
AMP had 25k page views yesterday, for context. 1.5m events were sent in the last month (via Chartio), and they're now going to Keen.

**Pull request merged**
