### PR TITLE
Node 6

### PR DESCRIPTION
**Pull request by commuterjoy**
/cc @adambraimbridge @georgecrawford

### CODE REVIEW

**Comment by georgecrawford** [comment]
Great, thanks Matt

**Comment by adambraimbridge** [comment]
Thanks 👍

**Comment by commuterjoy** [comment]
@adambraimbridge brave!

**Comment by commuterjoy** [comment]
https://circleci.com/gh/Financial-Times/spoor-enrichment/720

needed CI cache clearing

**Pull request merged**
