### PR TITLE
Cast browserVersion.version to real float

### PR DESCRIPTION
**Pull request by phamann**
In #263 we had to revert to using the full `device.browserVersion.version` rather than just the major. It turns out this can sometimes be a string such as `47.0.2526.106`. This has screwed the metrics. Therefore, we have to parse into a real float for the logic to work.

/cc @tom-parker @richard-still-ft

### CODE REVIEW

**Comment by chrisbrownuk** [comment]
@phamann 
I believe that we should capture the full browser version as a string.  This is what we were doing in Redshift, though we are now losing this information as a result of this change.  We already have other parsed values such as the integers "egest.annotations.deviceAtlas.osVersion.major" and "device_os_minor", "egest.annotations.deviceAtlas.osVersion.minor".

**Comment by commuterjoy** [comment]
@phamann need to be a little careful with changing downstream spoor stuff as it's effectively an API that several teams depend on.

@tom-parker @phamann @chrisbrownuk ...

Just to clarify - is the question should we treat "47.0.2526.106" as a string (which I think it is) or should we coerce it to a float?

**Comment by markstephens** [comment]
As long as you're not overwriting device atlas' version it's ok. It looks like the float is just used in your H2 calculation?

**Comment by chrisbrownuk** [comment]
Yes, it looks fine.  Sorry, I should have looked at the wider context and
not just the diff !

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 10 March 2016 at 09:12, Mark Stephens <notifications@github.com> wrote:

> As long as you're not overwriting device atlas' version it's ok. It looks
> like the float is just used in your H2 calculation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/pull/265#issuecomment-194746486>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by tom-parker** [comment]
:+1:  This is fine to go, as Mark said it's only used in the H2 stuff so won't change the actual annotations

**Pull request merged**
