### PR TITLE
rename

### PR DESCRIPTION
**Pull request by lc512k**

### CODE REVIEW

**Comment by commuterjoy** [comment]
+1

dependency ...

https://github.com/Financial-Times/spoor-voltdb/blob/master/deployment.xml#L38

**Comment by commuterjoy** [comment]
also, rubbish commit message ;)

**Comment by lc512k** [comment]
🙈

**Comment by lc512k** [comment]
Hm, I'll rename it something less specific, though. I forgot you were using it for volt.

**Pull request merged**
