### PR TITLE
Added FT region from new mapping

### PR DESCRIPTION
**Pull request by akilananb**
New Map Doesn’t have data compare with old data we had

[["AN", "US"], ["AP", "ASIA"], ["EU", "EUROPE"], ["FX", "EUROPE"], ["YU", "EUROPE”]]

These are the data missing in our old record

[["AX", "CEMEA"], ["BQ", "Americas"], ["CW", "Americas"], ["ME", "CEMEA"], ["BL", "Americas"], ["MF", "Americas"], ["SX", "Americas"], ["SS", "CEMEA"]]

and high level naming convention differs  eg...INDIA as ASIA,Europe and MIDDLEEAST as CEMEA

### CODE REVIEW

**Comment by commuterjoy** [comment]
+1

**Comment by commuterjoy** [comment]
It might be worth retaining these two as I think they are catch-alls for asia-pacific and europe ..

["AP", "ASIA"],
["EU", "EUROPE"]

**Comment by akilananb** [comment]
Does EUROPE should as is or CEMEA

**Comment by commuterjoy** [comment]
CEMEA
On 22 Jan 2016 08:25, "Akilan Anbu" <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Does EUROPE should as is or CEMEA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/pull/195#issuecomment-173841828>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Pull request merged**
