### PR TITLE
Bugfix for lost User GUIDs

### PR DESCRIPTION
**Pull request by markstephens**
We're not enriching user information when the GUID is sent manually as we only look for sessions/

cc @commuterjoy - No idea if I've done this correctly! Or you have a different pattern..

### CODE REVIEW

**Comment by commuterjoy** [comment]
Looks ok, but unsure why it's needed? Are there lots of events without sessions?

**Comment by commuterjoy** [comment]
Also, tests failing

**Comment by markstephens** [comment]
Yes, EmE.

**Comment by markstephens** [comment]
Yes, EmE just sends guids, and not sessions.
Tests fixed now.
Can you merge it?

**Pull request merged**
